### ISSUE TITLE
gulp install fails with: TypeError: node.serializeToString is not a function

### ISSUE THREAD

**Issue by syc0n** [CUModSquad/cu-ui-legacy#23]
I tested it on two different systems
git clone ...
npm install
gulp install

can someone please check if the same error appears?

``` error
cu-ui-character@0.1.0 /Users/nachtmann/priv/git/cu-ui/character
├── camelot-unchained@0.1.7  invalid
├── react@0.14.6
└── react-dom@0.14.6

[08:50:03] Finished 'install:npm' after 12 s
[08:50:03] Starting 'install:tsd'...
[08:50:03] Starting 'install:vs'...

/Users/nachtmann/priv/git/cu-ui/node_modules/xmldom/dom.js:906
     node.serializeToString(attributeSorter);
      ^
TypeError: node.serializeToString is not a function
    at XMLSerializer.serializeToString (/Users/nachtmann/priv/git/cu-ui/node_modules/xmldom/dom.js:906:7)
    at /source/util/generateVSProj.js:69:57
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

```

**Comment by syc0n** [comment]
quick fix was disabling  vsgen:

```
        build: {
          compress: false,
          vsgen: false,
```

in cu-build-tools/lib/util/loadConfig.js

**Comment by codecorsair** [comment]
fix is here, just waiting on it to be pushed to npm - https://github.com/jindw/xmldom/pull/148

**Comment by codecorsair** [comment]
enforcing 0.1.19 for xmldom.  0.1.20 broke it and a fix is waiting on a PR for that.
